### ISSUE TITLE
Few issues with new website

### ISSUE THREAD

**Issue by duttakapil** [coderplex/coderplex#121]
- [x] Next upcoming meetup is not showing in the Landing page - Events section (#118)
	> Implemented in #133 
- [ ] Default image used in the Events section of Landing page should be of higher quality and more relevant (#135)
- [x] /events page doesn't have the same loading bars as our current live website (#120)
	> Fixed in #132 
- [x] Images from meetup.com are not showing on the new /events page anymore (#119)
	> Fixed in #128 
- [x] On /events page, it's not showing more than two upcoming meetups. `Show more` button is not working (#126)
	> Fixed in #130 
- [x] On our /learn page, opening each new learning guide should change the title of the page to the title of the guide. (#125)
	> Implemented in #140 
- [x] The `view guide` button on our /learn page, for guides not on the website yet, should for the moment redirect to the markdown file of the guide [on our github](https://github.com/coderplex/learn) (#136)
	> Implemented in #140
