### ISSUE TITLE
Creating A Donation Page For Coderplex Foundation

### ISSUE THREAD

**Issue by duttakapil** [coderplex/coderplex#331]
Yesterday, the official bank account for Coderplex Foundation was finally opened with YES Bank. We can now operate it for all organization related income and expenses and also to receive donations. 

We need to put up a page or section on our website where members of the community, or any visitor of the website, can go and donate money to our non-profit org. 

### Tasks : 
- [ ] Design / mockup for the donation page or section 
- [ ] Creating the page and publishing it to the website
- [ ] Connecting it with the bank account (details provided below)

### Guidelines
We can use the following donation pages of global non-profit websites as guidelines for designing and publishing our own page : 
- [Khan Academy](https://www.khanacademy.org/donate)
- [Wikipedia](https://donate.wikimedia.org/w/index.php?title=Special:LandingPage&country=IN&uselang=en&utm_medium=sidebar&utm_source=donate&utm_campaign=C13_wikimediafoundation.org)
- [freeCodeCamp](https://donate.freecodecamp.org/)

### Why Do We Need A Donation Page
We have a very grand and challenging mission that we have set for ourselves at Coderplex, to improve the state of Tech Education in Hyderabad and gradually across India. We have a lot of really good ideas with a lot of potential that we want to work on to make this possible, but we lack the resources and team we need to execute these ideas, or to expand our operation even to a small degree. 

Our long term goal is to establish stable revenue streams for the organization, by offering recruitment serves to tech companies. Through this, we will be able to create value for our community members, by helping them get hired, as well as for the companies, by helping them hire quality developers from our community and finally also for ourselves, by earning the recruitment fee. There are a few more revenue generating ideas that we have, which we believe will be able to create value for everyone. 

But in the short term, we need as much support as we can get, from individuals as well as other organizations. This includes providing a option for our community members, or any visitor of our website, to support us by donating any sum that they are comfortable with. 

### Account details : 
Bank & Branch : YES Bank, Shivam Road
Account Number : 100194600000119
IFSC : YESB0001001

**Comment by duttakapil** [comment]
@vinaypuppal @M-ZubairAhmed

**Comment by addictd** [comment]
@duttakapil 
I can build a front end ui for the given job.
If no one is working and you( @duttakapil  ) confirm , than i can start working on it.

**Comment by vinaypuppal** [comment]
@duttakapil You can set up a donation page easily with Razorpay Pages which is released today. https://razorpay.com/payment-pages/

**Comment by duttakapil** [comment]
@vinaypuppal RazorPay and the like charge a commission fee of 2% correct? Is there a way to setup a donation page by circumventing the commission fee? I was thinking if we only relied on UPI payments it could work.

**Comment by vinaypuppal** [comment]
Yes, they may have an option to waive commission for NGO's, you can contact them and check.

**Comment by M-ZubairAhmed** [comment]
@duttakapil may be we can have phonepe upi page, i dont think they charge any fee

**Comment by duttakapil** [comment]
Yes, UPI is free, it doesn't have any transaction fee. We already have a UPI ID : `coderplex@yesbank`
